# title = ""
# description = ""

# The URL the site will be built for
base_url = "https://mushogenshin.com"

generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "anatole"

# Anatole
default_language = "en"

taxonomies = [{ name = "tags" }]

highlight_theme = "base16-ocean-light"

# # Anpu theme
# taxonomies = [
#     { name = "tags", rss = true },
#     { name = "categories", rss = true },
# ]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# # Anpu theme
# anpu_date_format = "%e %B %Y"
# anpu_menu_links = [
#     { url = "$BASE_URL/about/", name = "About" },
#     { url = "$BASE_URL/tags/", name = "Tags" },
# ]

# # Float theme
# copyright = "© Mushōgenshin 2023"
# web_fonts = "<link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@500;700&display=swap'>"
# google_analytics = false
# # google_analytics_id = "UA-XXXXXX-X"
# google_adsense = false
# # google_adsense_id = "ca-pub-XXXXXXXXXXXXXXXX"
# twitter_account = "@mushogenshin"

# Anatole
[extra.show]
ue_cpp = true
tags = true
links = true

# Anatole
[extra.social]
github = "mushogenshin"
# stackoverflow = ""         # use user_id
twitter = "mushogenshin"
# facebook = ""
instagram = "mushogenshin"
# dribbble = ""
# weibo = ""
linkedin = "hoan-trong-nguyen"
# flickr = ""

# Anatole
[languages.en]
title = "Hoan Nguyen"
description = "My thoughts on Art and Programming"
generate_feed = true
taxonomies = [{ name = "tags" }]

[languages.en.translations]
language_name = "English"
home = "Home"
about = "About"
ue_cpp = "UE C++"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"
